# Generated by Django 5.2.1 on 2025-05-10 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Банківська карта'), ('online', 'Онлайн-оплата'), ('transfer', 'Банківський переказ')], default='cash', max_length=20, verbose_name='Спосіб оплати')),
                ('status', models.CharField(choices=[('pending', 'Очікування'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('refunded', 'Повернуто')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Час завершення')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер транзакції')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Касир')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Номер чека')),
                ('fiscal_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фіскальний номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума податку')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Вміст чека')),
                ('is_printed', models.BooleanField(default=False, verbose_name='Надрукований')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment', verbose_name='Платіж')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-created_at'],
            },
        ),
    ]
