# Generated by Django 5.2.1 on 2025-05-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер столика')),
                ('capacity', models.IntegerField(verbose_name='Кількість місць')),
                ('location', models.CharField(help_text='Наприклад: Біля вікна, На терасі', max_length=100, verbose_name='Розташування')),
                ('status', models.CharField(choices=[('free', 'Вільний'), ('occupied', 'Зайнятий'), ('reserved', 'Зарезервований'), ('unavailable', 'Недоступний')], default='free', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клієнта')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клієнта')),
                ('reservation_date', models.DateField(verbose_name='Дата бронювання')),
                ('reservation_time', models.TimeField(verbose_name='Час бронювання')),
                ('duration', models.IntegerField(default=120, verbose_name='Тривалість (хвилин)')),
                ('guests_count', models.IntegerField(verbose_name='Кількість гостей')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tables.table', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-reservation_date', '-reservation_time'],
            },
        ),
    ]
