# Generated by Django 5.2.1 on 2025-05-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок відображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Зображення')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('preparation_time', models.IntegerField(default=15, verbose_name='Час приготування (хв)')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Вегетаріанська')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Гостра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
                'ordering': ['category', 'name'],
            },
        ),
    ]
