# Generated by Django 5.2.1 on 2025-05-10 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('ready', 'Готове'), ('delivered', 'Доставлене'), ('completed', 'Завершене'), ('cancelled', 'Скасоване')], default='new', max_length=20, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('refunded', 'Повернуто')], default='pending', max_length=20, verbose_name='Статус оплати')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Час оновлення')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Час завершення')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я клієнта")),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Знижка (%)')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tables.table', verbose_name='Столик')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Офіціант')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('ready', 'Готове'), ('delivered', 'Доставлене'), ('completed', 'Завершене'), ('cancelled', 'Скасоване')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Особливі побажання')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='menu.dish', verbose_name='Страва')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Елемент замовлення',
                'verbose_name_plural': 'Елементи замовлення',
            },
        ),
    ]
